name: 🐛 Bug Report
description: Report a bug in the setup scripts (macOS, Windows, Synology, Docker, Bash, PowerShell)
title: "[Bug] "
labels: ["type: bug", "priority: needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Please describe the issue as clearly as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is happening vs. what should happen?
      placeholder: |
        Examples:
        - "Running bash/darwin/brew.sh fails during Homebrew installation."
        - "Synology remote.sh does not execute cli.sh correctly."
        - "Windows Chocolatey install script fails to install package X."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can someone reliably reproduce the issue?
      placeholder: |
        1. Run script X
        2. Connect to Synology
        3. Error appears in terminal
      validations:
        required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Provide any terminal, PowerShell, Synology CLI, or GitHub Actions log output
      placeholder: |
        Example:
        ```
        Error: brew command not found
        ```
        or
        ```
        ssh: Permission denied (publickey,password)
        ```

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Operating system and version
      placeholder: |
        Examples:
        - macOS 15.x (M4)
        - Windows 11 PowerShell 7
        - Synology DSM 7.x
        - Docker version: 25.x
      validations:
        required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "🚨 Blocking (setup unusable)"
        - "⚠️ High (major functionality broken)"
        - "🟡 Medium (partial issue)"
        - "🔵 Low (minor or cosmetic)"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, logs, hardware details, etc.
      placeholder: |
        Example:
        "Synology DS920+, using SSH key authentication."
