style: github
template: CHANGELOG.tpl.md
info:
  title: "Changelog"
  repository_url: "https://github.com/munirmardinli/homelab"
options:
  commits:
    filters:
      Type: ["feat", "fix", "perf", "refactor", "docs", "chore", "style", "test"]
  commit_groups:
    title_maps:
      feat: "Features"
      fix: "Bug Fixes"
      perf: "Performance"
      refactor: "Refactoring"
      docs: "Documentation"
  header:
    pattern: "^([\\w\\s]+):\\s(.+)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
