name: Generate Changelog

on:
  workflow_dispatch: {}

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-chglog
        run: |
          curl -sSL https://github.com/git-chglog/git-chglog/releases/download/v0.15.4/git-chglog_0.15.4_linux_amd64.tar.gz | tar xz
          sudo mv git-chglog /usr/local/bin/

      - name: Generate Changelog
        run: |
          git-chglog --config .chglog/config.yml -o CHANGELOG.md
          cat CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "docs: update changelog"
            git push
          fi

      - name: Trigger Release Workflow
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: 'main'
            })
